generator:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/**/*'

widget:
- all:
  - changed-files:
    - any-glob-to-any-file: 'widget/src/**/*'

translation:
- all:
  - changed-files:
    - any-glob-to-any-file: 'src/translations/*'
