name: Suggestion
description: Suggest a new feature
labels: ["suggestion"]
body:
  - type: textarea
    id: suggestion
    attributes:
      label: What would you like to see added?
      description: Describe your idea.
    validations:
      required: true
